name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the project'
        required: true
        default: '{{cookiecutter.project_name}}'  # This will be replaced with the actual project name
      project_slug:
        description: 'Slug version of the project name'
        required: true
        default: '{{cookiecutter.project_slug}}'  # This will be replaced with the slug version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Log in to Docker Hub
        run: echo "${{ cookiecutter.dockerhub_token }}" | docker login -u "${{ cookiecutter.dockerhub_username }}" --password-stdin

      - name: Build & Push Docker image
        run: |
          # Use project_slug for Docker tag
          IMAGE_NAME="${{ cookiecutter.project_slug }}"
          docker build -t docker.io/${{ cookiecutter.dockerhub_username }}/${IMAGE_NAME}:latest .
          docker push docker.io/${{ cookiecutter.dockerhub_username }}/${IMAGE_NAME}:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml