---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.project_slug}}
  labels:
    app: {{cookiecutter.project_slug}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{cookiecutter.project_slug}}
  template:
    metadata:
      labels:
        app: {{cookiecutter.project_slug}}
    spec:
      containers:
        - name: {{cookiecutter.project_slug}}
          image: docker.io/{{cookiecutter.dockerhub_username}}/{{cookiecutter.project_slug}}:latest
          ports:
            - containerPort: 8080