apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.project_slug}}-service
spec:
  type: LoadBalancer
  selector:
    app: {{cookiecutter.project_slug}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
